@startuml Диаграмма активности для клиента
start
:Просмотреть товары;
:Положить товар в корзину;
:Выбрать оформление заказа;

if (Выбрана ли доставка) then (да)
    :Сделать оплату за доставку;
else (нет)
    :Оформить самовывоз;
endif
end
@enduml
