@startuml Диаграмма активности для клиента
start
:Просмотреть товары;
:Положить товар в корзину;
:Выбрать оформление заказа;

if (Выбрана ли доставка) then (да)
    :Сделать оплату только онлайн;
else (нет)
    :Сделать возможным\nоплату в пункте выдачи;
endif
end
@enduml
