@startuml Диаграмма прецедентов
    :Клиент: -up- (Просмотреть список товаров)
    :Клиент: -right- (Добавить товар в корзину)
    :Клиент: -down- (Просмотреть свою корзину)
    (Оформить заказ) as (Order)
    :Клиент: -left- (Order) 
    (Order) .down.> (Указать доставку и установку) : extend

    actor Администратор
    Администратор -up- (Просмотреть заказы)
    Администратор -right- (Закрыть заказ)
    Администратор -left- (Создать заявку на поставку товара)
    Администратор -left- (Закрыть заявку на поставку товара)
    Администратор -down- (Редактирование товаров)
@enduml
